package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.wanandroidapp.bean.HistoryArticleData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_ARTICLE_DATA".
*/
public class HistoryArticleDataDao extends AbstractDao<HistoryArticleData, Void> {

    public static final String TABLENAME = "HISTORY_ARTICLE_DATA";

    /**
     * Properties of entity HistoryArticleData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Title = new Property(0, String.class, "title", false, "TITLE");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property LastTime = new Property(2, String.class, "lastTime", false, "LAST_TIME");
        public final static Property Id = new Property(3, int.class, "id", false, "ID");
        public final static Property Author = new Property(4, String.class, "author", false, "AUTHOR");
    }


    public HistoryArticleDataDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryArticleDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_ARTICLE_DATA\" (" + //
                "\"TITLE\" TEXT," + // 0: title
                "\"URL\" TEXT," + // 1: url
                "\"LAST_TIME\" TEXT," + // 2: lastTime
                "\"ID\" INTEGER NOT NULL ," + // 3: id
                "\"AUTHOR\" TEXT);"); // 4: author
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_ARTICLE_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistoryArticleData entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String lastTime = entity.getLastTime();
        if (lastTime != null) {
            stmt.bindString(3, lastTime);
        }
        stmt.bindLong(4, entity.getId());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(5, author);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistoryArticleData entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String lastTime = entity.getLastTime();
        if (lastTime != null) {
            stmt.bindString(3, lastTime);
        }
        stmt.bindLong(4, entity.getId());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(5, author);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public HistoryArticleData readEntity(Cursor cursor, int offset) {
        HistoryArticleData entity = new HistoryArticleData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // title
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lastTime
            cursor.getInt(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // author
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistoryArticleData entity, int offset) {
        entity.setTitle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLastTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.getInt(offset + 3));
        entity.setAuthor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(HistoryArticleData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(HistoryArticleData entity) {
        return null;
    }

    @Override
    public boolean hasKey(HistoryArticleData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
